---
abstract: 'Optimistic locking support for DBIx::Class'
author:
  - 'Brian Phillips <bphillips@cpan.org>'
build_requires:
  Cwd: 0
  DBIx::Class::Schema: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-OptimisticLocking
recommends: {}
requires:
  Carp: 0
  DBIx::Class: 0
resources:
  repository: http://github.com/brianphillips/dbix-class-optimisticlocking
version: 0.02
